  version: '3.1'

  services:

    datatbase:
      image: "postgres"
      ports:
        - 8080:8080
      environment:
        POSTGRES_DB: "db"
        POSTGRES_USER: "student"
        POSTGRES_PASSWORD: "aqahw7"
